apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-api-deployment
  labels:
    app: user-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-api
  template:
    metadata:
      labels:
        app: user-service-api
    spec:
      containers:
      - name: user-service-api
        image: zzkk/user-service-api
        ports:
        - containerPort: 5000